services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    restart: unless-stopped
    ports:
    - 8096:8096/tcp
    - 7359:7359/udp
    volumes:
    - ./data/config:/config
    - ./data/cache:/cache
    - /srv/media:/media:ro
